<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto [
<!ELEMENT aeropuerto (nombre, vuelos, fecha)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vuelos (vuelo+)>
    <!ELEMENT vuelo (diario?, origen, destino, salida, llegada)>
        <!ATTLIST vuelo cod ID #REQUIRED>
        <!ATTLIST vuelo estado (C | E | R) "E">
        <!ELEMENT diario EMPTY>
        <!ELEMENT origen (#PCDATA)>
        <!ELEMENT destino (#PCDATA)>
        <!ELEMENT salida (#PCDATA)>
        <!ELEMENT llegada (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
]>
<aeropuerto>
    <nombre>JFK</nombre>
    <vuelos>
        <vuelo cod="V22" estado="R">
            <diario/>
            <origen>New York</origen>
            <destino>Chicago</destino>
            <salida>9:30</salida>
            <llegada>11:30</llegada>
        </vuelo>
        <vuelo cod="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <salida>10:15</salida>
            <llegada>11:15</llegada>
        </vuelo>
    </vuelos>
    <fecha>20/12/2013</fecha>
</aeropuerto>