<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudades [
    <!ELEMENT ciudad (nombre,pais)*>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT pais (#PCDATA)>
        <!ATTLIST pais continente CDATA #REQUIRED>
]>
 <ciudades>
    <ciudad>
        <nombre>Nueva Dehli</nombre>
        <pais continente="Ásia">India</pais>
    </ciudad>

    <ciudad>
        <nombre>Lisboa</nombre>
        <pais continente="Europa">Portugal</pais>
    </ciudad>

    <ciudad>
        <nombre>El Cairo</nombre>
        <pais continente="África">Egipto</pais>
    </ciudad>
</ciudades>