<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
    <!ELEMENT futbol (equipo)*>
    <!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT entrenador EMPTY>
    <!ELEMENT jugadores (jugador*)>
    <!ELEMENT jugador (nombre, nacionalidad)>
    <!ATTLIST jugador posicion (portero | defensa | medio | delantero)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacionalidad (#PCDATA)>
]>
<futbol>
    
    <equipo>
        <nombre>Real Racing Club</nombre>
        <ciudad>Santander</ciudad>
        <entrenador/>
        
        <jugadores>
            <jugador posicion="portero">
                <nombre>Iván Crespo Secunza</nombre>
                <nacionalidad>española</nacionalidad>
            </jugador>

            <jugador posicion="defensa">
                <nombre>Figueras</nombre>
                <nacionalidad>española</nacionalidad>
            </jugador>
        </jugadores>
    </equipo>
    
    <equipo>
        <nombre>Real Zaragoza</nombre>
        <ciudad>Zaragoza</ciudad>
        <entrenador/>
        
        <jugadores>
            <jugador posicion="medio">
                <nombre>Zapater</nombre>
                <nacionalidad>española</nacionalidad>
            </jugador>

            <jugador posicion="delantero">
                <nombre>Linares</nombre>
                <nacionalidad>española</nacionalidad>
            </jugador>
        </jugadores>
    </equipo>
</futbol>