=== pinsolares/moduloxml/h3_12.dtd
<!-- DTD de un concesonario -->
<!ELEMENT coches (coche+)>
<!ELEMENT coche (carroceria, motor, especificaciones)>
<!ATTLIST coche numbastidor ID #REQUIRED>

<!-- CARROCERIA -->
<!ELEMENT carroceria (color, numpuertas, cabrio?)>
<!ELEMENT color (#PCDATA)>
<!ATTLIST color tipo (metalizado | basico) #REQUIRED>
<!ELEMENT numpuertas (#PCDATA)>
<!ELEMENT cabrio EMPTY>

<!-- MOTOR -->
<!ENTITY % consumo "(cdiesel | cgasolina | celectrico | cmixto)+">
<!ELEMENT motor (cilindrada, cv, %consumo;)>
<!ELEMENT cilindrada (#PCDATA)>
<!ELEMENT cv (#PCDATA)>
<!ELEMENT cdiesel (#PCDATA)>
<!ELEMENT cgasolina (#PCDATA)>
<!ELEMENT celectrico (#PCDATA)>
<!ELEMENT cmixto (#PCDATA)>

<!-- ESPECIFICACIONES -->
<!ELEMENT especificaciones (marca, modelo, estado)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT estado EMPTY>
<!ATTLIST estado id (nuevo | km0 | usado) #REQUIRED>

=== pinsolares/moduloxml/h3_12.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE coches SYSTEM "h3_12.dtd">
<coches>
  <coche numbastidor="B1">
    <carroceria>
    <color tipo="metalizado">rojo</color>
    <numpuertas>5</numpuertas>
    </carroceria>
    <motor>
      <cilindrada>mucha</cilindrada>
      <cv>muchos</cv>
      <cdiesel>6,5</cdiesel>
    </motor>
    <especificaciones>
      <marca>Peugeot</marca>
      <modelo>206 HDI</modelo>
      <estado id="usado"/>
    </especificaciones>
  </coche>
</coches>
