=== pinsolares/moduloxml/pagos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="pagos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" maxOccurs="3" default="A">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="dni" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:maxLength value="10"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="fechaNacimiento">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:date">
                <xs:attribute name="edad">
                  <xs:simpleType>
                    <xs:restriction base="xs:integer">
                      <xs:minInclusive value="16"/>
                      <xs:maxInclusive value="24"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="hora" type="xs:time" maxOccurs="unbounded"/>
        <xs:element name="precio" type="xs:double"/>
        <xs:element name="cantidad" type="xs:integer" fixed="678"/>
        <xs:element name="pagado" type="xs:boolean" default="false"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pinsolares/moduloxml/pagos.xml
<?xml version="1.0" encoding="UTF-8"?>
<pagos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="pagos.xsd">
   <nombre dni="77888999A">Javier Toledano</nombre>
   <fechaNacimiento edad="20">2009-02-04</fechaNacimiento>
   <hora>23:55:15</hora>
   <hora>23:55:15</hora>
   <precio>123.56</precio>
   <cantidad>678</cantidad>
   <pagado>true</pagado>
</pagos>
